
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.0/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    // SqlDelight plugin to generate kotlin code for database
    alias(libs.plugins.sql.delight)
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(platform(libs.http4k.bom))
    implementation(libs.http4k.core)
    implementation(libs.http4k.moshi)
    implementation(libs.http4k.jetty)
    implementation(libs.http4k.config)
    implementation(libs.sqldelight.jdbc)
    implementation(libs.hikari)
    runtimeOnly(libs.mysql.driver) // we need this driver so that Hikari our datasource can talk to actual mariadb using this driver

    testImplementation(libs.http4k.kotest)
    testImplementation(libs.http4k.testing.approval)
    testImplementation(libs.h2.db) // we are using in memory database for tests to avoid containers running in test using test containers
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest("2.2.21")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

kotlin {
    jvmToolchain(21)
}

application {
    // Define the main class for the application.
    mainClass = "org.example.AppKt"
}

// sqldelight configuration
sqldelight {
    databases {
        create("Database") {
            packageName.set("org.example")
            dialect("app.cash.sqldelight:mysql-dialect:2.2.1")
        }
    }
}
