/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import app.cash.sqldelight.driver.jdbc.asJdbcDriver
import com.auth0.jwt.JWT
import com.auth0.jwt.JWTVerifier
import com.auth0.jwt.algorithms.Algorithm
import com.zaxxer.hikari.HikariConfig
import com.zaxxer.hikari.HikariDataSource
import org.example.api.api
import org.example.config.audience
import org.example.config.dbPassword
import org.example.config.dbUrl
import org.example.config.dbUser
import org.example.config.issuer
import org.example.config.publicKey
import org.example.config.redirectUri
import org.example.repository.CatsRepository
import org.example.service.CatService
import org.example.web.webApp
import org.http4k.base64DecodedArray
import org.http4k.config.Environment
import org.http4k.routing.routes
import org.http4k.server.Jetty
import org.http4k.server.asServer
import java.security.KeyFactory
import java.security.interfaces.RSAPublicKey
import java.security.spec.X509EncodedKeySpec
import java.time.Clock
import java.util.*

fun createApp(
    env: Environment,
    clock: Clock,
    uuidGenerator: () -> UUID = { UUID.randomUUID() }
): CatService {

    val dbConfig = HikariConfig().apply {
        jdbcUrl = env[dbUrl]
        username = env[dbUser]
        password = env[dbPassword].use { it.toString() }
    }

    val datasource = HikariDataSource(dbConfig)
        .asJdbcDriver()
        .also { Database.Schema.create(it) }
        .let { Database(it) }

    // you can use Jetty or JettyLoom which uses virtual threads
    // .asServer(SunHttp(0)) - by default http4k comes with SunHttpServer, which should not be used in production
    // if you want to use a different server, use one from this list: https://www.http4k.org/ecosystem/http4k/reference/servers/
    return CatService(
        CatsRepository(datasource.catsQueries),
        clock,
        uuidProvider = uuidGenerator,
        jwtVerifier = getJwtVerifier(env)
    )

}

fun getJwtVerifier(env: Environment): JWTVerifier {
    val keySpec = X509EncodedKeySpec(env[publicKey].base64DecodedArray())
    val rsaPublicKey = KeyFactory.getInstance("RSA").generatePublic(keySpec)
    val algorithm: Algorithm = Algorithm.RSA256(rsaPublicKey as RSAPublicKey, null)
    return JWT.require(algorithm) // specify any specific claim validations
        .withIssuer(env[issuer])
        .withAudience(env[audience] )
        .build()
}

fun main() {
    val env = Environment.ENV
    val catsApp = createApp(env, Clock.systemUTC()).api()

    val webApp = webApp(
        env[audience],
        env[redirectUri]
    )

    routes(webApp, catsApp)
        .asServer(Jetty(8080))
        .start()
}
